# Generated by Django 4.2.30 on 2026-06-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='compoleted',
            new_name='completed',
        ),
    ]
